function alpha = mixed_folded_normal_kernel_velocity_profile_with_decay ...
    (t, mu0, sigma0, lambda, Ns)

% Normalization constant
[w, mu, sigma, normalization_constant] = ...
    mixed_folded_normal_kernel_velocity_profile_with_decay_aux ...
    (mu0, sigma0, lambda, Ns);

% Subkernels
alpha_i = (exp(-0.5*((t - mu)./sigma).^2) + exp(-0.5*((t + mu)./sigma).^2)) ...
    ./(sigma*sqrt(2*pi));

% Kernel
alpha = sum(w.*exp(-lambda*t).*alpha_i, 1) ...
    /sum(w.*normalization_constant);